---

git_repo          : 'git@github.com:umd-lib/drum'
git_branch        : 'master'
mvn_version       : '3.0.5'
mvn_params        : '-Denv=vagrant'

# NOTE: if you change 'git_branch' above, you MAY need to modify this 'ant_installer_dir'
# setting. It must be set to the directory where the Ant-based installer ends up, after
# 'mvn package' is run. For now, this is hardcoded (see DS-1760 ticket).
ant_installer_dir : '/apps/drum'
admin_firstname   : 'DrumDev'
admin_lastname    : 'Admin'
admin_email       : 'drumdev+admin@gmail.com'
admin_passwd      : 'vagrant'
admin_language    : 'en'

